### ISSUE TITLE
Vanilla maps become images that were previously loaded.

### ISSUE THREAD

**Issue by Cubex61** [zDevelopers/ImageOnMap#125]
Any vanilla maps become image maps that were already created. This goes for treasure maps and empty maps. I've seen some other people having this issue as well. Has anything been found to fix it?

**Comment by Vlammar** [comment]
It's caused by a fail update of the idcounts.dat file located in world/data . Why this happen? we don't realy know how but it seams that the server can take a pretty long time to write in this file and create all map_XX.dat files (may be a spigot bug but not sure). Crash or suddent stop can cause this issue, to fix it you have two possibilities. 
1) Check by hand all player map store and edit them (remove mapID>idcounts) 
2) A simple fix is to edit the file idcounts.dat and set it to a value greater than the biggest used in player map store (easyiest). Use a nbt editor like this one https://irath96.github.io/webNBT/ you have to drag and drop your idcounts and manually update the counter.
