### ISSUE TITLE
The Bug about every single map automatically rotate right in the newest 4.0 version, and few more questions

### ISSUE THREAD

**Issue by CKFA** [zDevelopers/ImageOnMap#133]
As the title mentioned, The single map automatically rotate right when i put on the item frame in the newest 4.0 version and this problem does not exist on the 4.0 pre2 version. 

In addition, is there any way to hide the name from the itemframe? It shows the name when i placed on the item frame but i don't want.

Also, there is the suggestion, make a new function for /map inventory which enable to player can sort out the maps in different orders if they got so much and the First & Last page hotkey.

Thanks.

**Comment by Vlammar** [comment]
Hi for your bug this will be fixed in the next update. The name issue is also a bug fixed in the upcomming version. 
Sorting maps can be a thing (or having a search option) but I'm not really convinced by this idea to manualy change map order, changing from one page to another will be tedious. Adding a button to sort by date or by alphebetical order can be nice.

**Comment by Vlammar** [comment]
Fixed in 4.1
