### ISSUE TITLE
image on map stopped working 

### ISSUE THREAD

**Issue by someloserr** [zDevelopers/ImageOnMap#155]
hey i have a server on minehut and i use the map on image plugin and it was working fine then it stopped working, the maps are still there but we cannot see them, this happened on the last server of mine as well,

**Comment by AmauryCarrade** [comment]
Hello

This is a problem on Minehut side—you're not the first to report it so I know exactly what is happening.

I guess you got the following error in your server console:

```
Error occurred while enabling ImageOnMap v4.0 (Is it up to date?)
java.security.AccessControlException: pkg/raw => This functionality is no longer supported on Minehut
    at PlayerServerSecurityManager$Active.checkRestrictedOnPlugin(PlayerServerSecurityManager.java:42) ~[?:?]
    at PlayerServerSecurityManager$Active.checkPackageAccess(PlayerServerSecurityManager.java:105) ~[?:?]
    at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:174) ~[?:?]
        ...
    at fr.moribus.imageonmap.tools.reflection.Reflection.instantiate(Reflection.java:480) ~[?:?]
    at fr.moribus.imageonmap.components.i18n.translators.Translator.getInstance(Translator.java:392) ~[?:?]
        ...
```

Minehut disabled (and that's really surprising) a fundamental component of Java programs (including plugins) called reflection. It's rather complicated, but for the idea it's what we use to hook into the Minecraft server itself and do advanced things Spigot/Paper does not allow us to do.

We (and a lot of other plugins) use this feature a lot. For advanced items management (think about the special maps ImageOnMap gives), some GUIs (this sign GUI to rename a map), translations (so everyone can use IoM in its own language, even on the same server). It would be a huge task (like really huge) to rewrite ImageOnMap without that.
That's why multiple plugins suddenly broke, as some of you mentioned. Reflection is widely used.

That's not only ImageOnMap. Some popular plugins like WorldEdit or WorldGuard massively use reflection too. They are probably broken too.

[Here it say (not really clear) it was some kind of error and it should be fixed by restarting the server?](https://forums.minehut.com/topic/36723-when-i-do-plugins-some-of-them-are-red-world-edit-image-on-map-world-guard-i-have-the-logs-if-anyone-knows-how-to-fix-it-pls-help/) The error in the log is the same. If it's not, please do ask the Minehut technical staff if they can remove this restriction. Feel free to quote this message if you want.

I'll close this issue as this is not something we can fix on our side, but you can still reply if needed, for anything.
