### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by Kas-tle** [zDevelopers/ImageOnMap#37]
I have given the groups I want the permission node imageonmap.userender, but for some reason permissions do not work. I have to be oped to be able to use any of the plugin commands. The server uses GroupManagerX for permissions, and is running the following plugins: ZLib, AlwaysDay, FastAsyncWorldEdit, Essentials, VoxelSniper, ImageOnMap, EssentialsChat, GroupManager, EssentialsAntiBuild, Vault, EssentialsSpawn, Multiverse-Core, dynmap, WorldEdit, SignColors, EssentialsProtect, HeadsPlugin, WorldBorder, HeadsInventory. I wish I could give you an error, but the console generates nothing.

**Comment by Feptoid** [comment]
I am also having this issue.  Running 1.11.2

**Comment by plinfut** [comment]
Any news on this? On my server it is also only available to ops despite others having the documented permission node.

**Comment by RoyCurtis** [comment]
Was looking at this plugin for somebody else, and saw this issue about the permission node.

After investigating, I've found the permission node `imageonmap.maptool` grants access to `/tomap`, instead of `imageonmap.userender`. The problem with this, is that it also grants permission to the entire `/maptool` command, allowing players to delete maps. So this is not really useful, but worth noting anyway...

I found this out by following this trail, more or less:

* https://github.com/zDevelopers/ImageOnMap/blob/620f33454aec50b179d83fba1539ce8de47c2d11/src/main/java/fr/moribus/imageonmap/ImageOnMap.java#L112
* https://github.com/zDevelopers/zLib/blob/a8f7f9dfb4420eefdb3fd08618edbf5053596ae3/src/main/java/fr/zcraft/zlib/components/commands/Commands.java#L46
* https://github.com/zDevelopers/zLib/blob/b4292bff14cd51578bca2ddd57391d27b55fb33a/src/main/java/fr/zcraft/zlib/components/commands/Command.java#L123

**Comment by AmauryCarrade** [comment]
The permissions are now fully fixed. Sorry for the delay to update this!
